### ISSUE TITLE
Tabs are too small with tiny font

### ISSUE THREAD

**Issue by p00f** [felkr/firefox-minima#1]

**Comment by p00f** [comment]
I think increasing tab size a bit and using monospace font for tabs will fix this

**Comment by felkr** [comment]
![](https://i.imgur.com/6KkuNwg.png)

I've made the default font monospace now and made it a bit bigger. Also, tabs now take the full space by default, like qutebrowser. You can configure the theme using CSS variables on the top too.

Regarding the issue with the border, I've noticed that some Firefox Themes/colors don't show a border for some reason. I used [Pywalfox](https://addons.mozilla.org/en-US/firefox/addon/pywalfox/) for the screenshots, but others like Dracula work too, while some themes weirdly don't display a border. I'll look into the making this more consistent in the future.

If you have any further questions or suggestions, feel free to add them, otherwise you can close this issue
